# Logger options
log_iter: 100                  # How often to log the training loss
val_iter: 500                 # How often to validate testing and save output images during training

# Optimization options
max_iter: 1200                # Maximum number of training iterations
batch_size: 1                 # Batch size
loss: L2
optimizer: Adam               # Optimizer for trainings
weight_decay: 0.0001          # Weight decay
beta1: 0.9                    # Adam parameter
beta2: 0.999                  # Adam parameter
lr: 0.0001                    # Initial learning rate



################### 2D CT Image ###################
# Model options (2D CT)
model: SIREN                  # Options for MLP models [FFN | SIREN]
net:
  network_input_size: 1024     # Input size for network
  network_output_size: 1
  network_depth: 8            # Depth of MLP layers
  network_width: 256          # Width of MLP layers

encoder:
  embedding: gauss            #  Input embedding method
  scale: 4
  embedding_size: 512         # Embedding size for input Fourier feature encoding
  coordinates_size: 2


# Data
data: spec35
energy: E2
img_size: 256     # (92, 256, 256)
